# Generated by Django 6.1 on 2026-09-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("first_name", "last_name"), name="unique_user_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                ("evaluation_id", models.AutoField(primary_key=True, serialize=False)),
                ("injury_description", models.CharField(max_length=100)),
                ("pain_level", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "date"), name="unique_user_evaluation_date"
                    )
                ],
            },
        ),
    ]
