# Generated by Django 6.1 on 2026-09-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "training_plan_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "workout_session_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "training_plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rehab.trainingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("exercise_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("difficulty", models.IntegerField()),
                ("workout_sessions", models.ManyToManyField(to="rehab.workoutsession")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="trainingplan",
            constraint=models.UniqueConstraint(
                fields=("user_id", "name", "start_date"),
                name="unique_user_training_plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutsession",
            constraint=models.UniqueConstraint(
                fields=("training_plan_id", "date"), name="unique_training_session_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("name", "difficulty"), name="unique_exercise_difficulty"
            ),
        ),
    ]
