# Generated by Django 6.1 on 2026-09-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0002_rename_exercise_id_exercise_exercise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="exercise",
            new_name="exercise_id",
        ),
        migrations.RenameField(
            model_name="trainingplan",
            old_name="training_plan",
            new_name="training_plan_id",
        ),
        migrations.RenameField(
            model_name="trainingplan",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="workoutsession",
            old_name="training_plan",
            new_name="training_plan_id",
        ),
        migrations.RenameField(
            model_name="workoutsession",
            old_name="workout_session",
            new_name="workout_session_id",
        ),
    ]
