# Generated by Django 6.1 on 2026-09-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="exercise_id",
            new_name="exercise",
        ),
        migrations.RenameField(
            model_name="trainingplan",
            old_name="training_plan_id",
            new_name="training_plan",
        ),
        migrations.RenameField(
            model_name="trainingplan",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="workoutsession",
            old_name="training_plan_id",
            new_name="training_plan",
        ),
        migrations.RenameField(
            model_name="workoutsession",
            old_name="workout_session_id",
            new_name="workout_session",
        ),
    ]
