# Generated by Django 6.1 on 2026-09-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0003_rename_exercise_exercise_exercise_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="workout_sessions",
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="exercises",
            field=models.ManyToManyField(to="rehab.exercise"),
        ),
    ]
