# Generated by Django 6.1 on 2026-09-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0004_remove_exercise_workout_sessions_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workoutsession",
            name="unique_training_session_date",
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="workout_sessions",
            field=models.ManyToManyField(to="rehab.workoutsession"),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="workoutsession",
            constraint=models.UniqueConstraint(
                fields=("name", "date"), name="unique_workout_session_date"
            ),
        ),
        migrations.RemoveField(
            model_name="workoutsession",
            name="training_plan_id",
        ),
    ]
